workflows: db-backup: check if python is installed
Signed-off-by: Mateusz Korzeniowski <m4teusz.korzeniowski@gmail.com>

diff --git a/.github/workflows/db-backup.yml b/.github/workflows/db-backup.yml
--- a/.github/workflows/db-backup.yml
+++ b/.github/workflows/db-backup.yml
@@ -27,6 +27,31 @@ jobs:
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_KEY }}
           script: |
+            set -e
             cd /opt/e-learning-app/
+            
+            if ! command -v python3 &> /dev/null; then
+              echo "python3 not found. Installing..."
+              apt update
+              apt install -y python3
+            else
+              echo "python3 is already installed."
+            fi
+            
+            if ! command -v pip3 &> /dev/null; then
+              echo "pip3 not found. Installing..."
+              apt install -y python3-pip
+            else
+              echo "pip3 is already installed."
+            fi
+            
+            if ! python3 -c "import dotenv" &> /dev/null; then
+              echo "python-dotenv not found. Installing..."
+              pip3 install --quiet python-dotenv
+            else
+              echo "python-dotenv already installed."
+            fi
+            
+            echo "Running backup
             python3 backup_db.py
 
